<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工信息管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"chuqin"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"奖惩管理",
                        "menuJump":"列表",
                        "tableName":"jiangcheng"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"绩效管理",
                        "menuJump":"列表",
                        "tableName":"jixiao"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工资管理",
                        "menuJump":"列表",
                        "tableName":"xinzi"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"离职退休费用管理",
                        "menuJump":"列表",
                        "tableName":"butie"
                    }
                ],
                "menu":"离职退休费用管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训管理",
                        "menuJump":"列表",
                        "tableName":"cultivate"
                    }
                ],
                "menu":"培训管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"岗位管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_gangwei"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工种管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_gongzhong"
                    }
                ],
                "menu":"系统管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"考勤管理",
                        "menuJump":"列表",
                        "tableName":"chuqin"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"奖惩管理",
                        "menuJump":"列表",
                        "tableName":"jiangcheng"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"绩效管理",
                        "menuJump":"列表",
                        "tableName":"jixiao"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"工资管理",
                        "menuJump":"列表",
                        "tableName":"xinzi"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"培训管理",
                        "menuJump":"列表",
                        "tableName":"cultivate"
                    }
                ],
                "menu":"培训管理"
            }
            
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
